AllCops:
  TargetRubyVersion: 2.2
  TargetRailsVersion: 4.2
  Exclude:
    - 'Rakefile'

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'db/seeds.d/**'

Style/FormatStringToken:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/**/engine.rb'
    - 'test/**/*'

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/**/engine.rb'
    - 'test/**/*'
